--INSTEAD OF LIMIT & OFFSET, OFFSET & FETCH is used in MSsql
SELECT * FROM [User] ORDER BY User_id
OFFSET 2 ROWS
FETCH NEXT 2 ROWS ONLY;

--INSTEAD OF LIMIT & OFFSET, OFFSET & FETCH is used in MSsql
SELECT * FROM Ticket ORDER BY Ticket_id
OFFSET 1 ROWS
FETCH NEXT 1 ROWS ONLY;

--for only LIMIT without OFFSET
SELECT COUNT(*) AS TotalTickets FROM Ticket;
SELECT TOP 2 * FROM Ticket;
